name: 'Jenkins Job Trigger'
description: 'Trigger a Jenkins job'
branding:
  icon: 'terminal'
  color: 'green'
inputs:
  url:
    description: 'Jenkins full URL including http/https protocol'
    required: true
  user_name: 
    description: 'User name of Jenkins'
    required: true
  api_token:
    description: 'Jenkins API token'
    required: true
  job_name:
    description: 'Job name'
    required: true
  wait:
    description: 'Waiting for job completion or not'
    required: false
    default: "true"
  timeout:
    description: 'Timeout (seconds) for github action. Set 600s as default'
    required: false
    default: "600"
  
runs:
  using: 'jenkinsfile'
  steps:
    - id: testjob
      run: |
        #Parameters
        urlOfJenkinsServer="${{ inputs.url }}"
        jenkinsJobName="${{ inputs.job_name }}"
        userName=${{ inputs.user_name }}
        password=${{ inputs.api_token }}
